import io

from Utils.logger import logger

"""
Get a map with the frequency as the key, and a list of positions of antenna
"""

if __name__ == "__main__":
    filepath = input("Input File Path: ")

    file = io.StringIO(
        """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""")


    try:
        file = open(filepath)
    except:
        pass